env:
  global:
  - DEBUG='* -mocha:* -superagent -express:* -base:validator -base:entity'
language: node_js
node_js:
- '0.10'
sudo: false
script: echo Skipping build to preserve resources
before_install:
- openssl aes-256-cbc -K $encrypted_78939d397eb0_key -iv $encrypted_78939d397eb0_iv
  -in taskcluster-auth.conf.json.enc -out taskcluster-auth.conf.json -d
- gpg --import pmoore.gpg.key
- gpg -a --encrypt --recipient pmoore@mozilla.com README.md
- cat README.md.asc
